kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
name: milestone-cluster
nodes:
- role: control-plane
  extraPortMappings:
  - containerPort: 80
    hostPort: 80
  - containerPort: 443
    hostPort: 443
  - containerPort: 30007
    hostPort: 30007
- role: worker
- role: worker