apiVersion: v1
kind: ConfigMap
metadata:
  name: bv-db-init
  namespace: bv-app
data:
  init.sql: |
    CREATE TABLE IF NOT EXISTS users (id INT AUTO_INCREMENT PRIMARY KEY, name VARCHAR(255));
    INSERT INTO users (id, name) VALUES (1, 'Brent Verlinden');
