apiVersion: v1
kind: Secret
metadata:
  name: db-secret
  namespace: milestone-app
type: Opaque
stringData:
  DB_HOST: "mariadb-service"
  DB_USER: "appuser"
  DB_PASSWORD: "apppassword"
  DB_NAME: "milestone"
  MYSQL_ROOT_PASSWORD: "rootpassword"