apiVersion: v1
kind: Secret
metadata:
  name: bv-db-secret
  namespace: bv-app
type: Opaque
stringData:
  DB_HOST: "bv-mariadb-service"
  DB_USER: "appuser"
  DB_PASSWORD: "apppassword"
  DB_NAME: "milestone"
  MYSQL_ROOT_PASSWORD: "rootpassword"
